//these 100 intrger will be generated by computer.
#include<stdio.h>
void main(){
	int i;
    int a[100];
    for(i=0;i<10;i++){
        scanf("%d",&a[i]);

    }
    a[11] = 0;
    printf("new babies");
    for(i=0;i<100;i++){
        printf("%d\n",a[i]);
    }

}